### ISSUE TITLE
Zoom control

### ISSUE THREAD

**Issue by wider2** [car2go/AnyMaps#21] opened 2018-06-26 06:02 UTC
Actually, many map services offer in the corner 'Zoom control'
we can click at + or -

Is it possible to implement it in AnyMap?

mMap.getUiSettings().setZoomControlsEnabled(true);

**Comment by Diolor** [comment] 2018-06-27 22:45
There's no such feature. But would be easy if you like to implement it

**Comment by Diolor** [comment] 2018-06-27 22:46
Closing as duplicate of #15

**Closed as completed by Diolor** 2018-06-27 22:46 UTC
